### ISSUE TITLE
Remove phpunit dependency

### ISSUE THREAD

**Issue by fefas** [bauhausphp/assert-psr-response#3]
The only reason for using `phpunit` as dependency is the `assertJsonStringEqualsJsonString`, but it is not a good idea to have such dependency only because one function.

The problem is that `assertJsonStringEqualsJsonString` assert exception provides a very useful diff (see #1)... which means the diff has to be self implemented to remove this dependency.

**Comment by edudobay** [comment]
I believe that the diff functionality in PHPUnit is realized by the [exporter](https://github.com/sebastianbergmann/exporter) and [comparator](https://github.com/sebastianbergmann/comparator) packages. Maybe you could at least drill down your dependencies to the necessary subset :)
